Repository picnicml/doddle-model, pull requests merged in 2019-09, with the labels that each got.

#71 Scala 2.13 support
  .circleci/config.yml
  build.sbt
  project/Dependencies.scala
  src/main/scala-2.12-/io/picnicml/doddlemodel/CrossScalaCompat.scala
  src/main/scala-2.13+/io/picnicml/doddlemodel/CrossScalaCompat.scala
  src/main/scala/io/picnicml/doddlemodel/data/DatasetUtils.scala
  src/main/scala/io/picnicml/doddlemodel/data/package.scala
  src/main/scala/io/picnicml/doddlemodel/dummy/classification/MostFrequentClassifier.scala
  src/main/scala/io/picnicml/doddlemodel/dummy/classification/StratifiedClassifier.scala
  src/main/scala/io/picnicml/doddlemodel/metrics/RankingMetrics.scala
  src/main/scala/io/picnicml/doddlemodel/modelselection/DataSplitter.scala
  src/main/scala/io/picnicml/doddlemodel/modelselection/GroupKFoldSplitter.scala
  src/main/scala/io/picnicml/doddlemodel/modelselection/HyperparameterSearch.scala
  src/main/scala/io/picnicml/doddlemodel/modelselection/KFoldSplitter.scala
  src/test/scala/io/picnicml/doddlemodel/integration/LinearRegressionTest.scala
  src/test/scala/io/picnicml/doddlemodel/integration/LogisticRegressionTest.scala
  src/test/scala/io/picnicml/doddlemodel/integration/PoissonRegressionTest.scala
  src/test/scala/io/picnicml/doddlemodel/integration/SoftmaxClassifierTest.scala
  src/test/scala/io/picnicml/doddlemodel/modelselection/HyperparameterSearchTest.scala
  src/test/scala/io/picnicml/doddlemodel/pipeline/PipelineTest.scala
Labels: enhancement

#68 Additional preprocessors
  src/main/scala/io/picnicml/doddlemodel/preprocessing/Binarizer.scala
  src/main/scala/io/picnicml/doddlemodel/preprocessing/Normalizer.scala
  src/main/scala/io/picnicml/doddlemodel/preprocessing/Norms.scala
  src/main/scala/io/picnicml/doddlemodel/preprocessing/RangeScaler.scala
  src/test/scala/io/picnicml/doddlemodel/preprocessing/BinarizerTest.scala
  src/test/scala/io/picnicml/doddlemodel/preprocessing/NormalizerTest.scala
  src/test/scala/io/picnicml/doddlemodel/preprocessing/NormsTest.scala
  src/test/scala/io/picnicml/doddlemodel/preprocessing/RangeScalerTest.scala
Labels: enhancement

#88 Fix featureIndex.subset() api
  src/main/scala/io/picnicml/doddlemodel/data/Feature.scala
  src/test/scala/io/picnicml/doddlemodel/data/FeatureTest.scala
Labels: enhancement

#92 Minimal refactoring
  src/main/scala/io/picnicml/doddlemodel/linear/LinearRegression.scala
  src/main/scala/io/picnicml/doddlemodel/linear/LogisticRegression.scala
  src/main/scala/io/picnicml/doddlemodel/linear/PoissonRegression.scala
  src/main/scala/io/picnicml/doddlemodel/linear/SoftmaxClassifier.scala
Labels: enhancement

#94 Merge multiple apply functions into ones with default parameters
  src/main/scala/io/picnicml/doddlemodel/linear/LinearRegression.scala
  src/main/scala/io/picnicml/doddlemodel/linear/LogisticRegression.scala
  src/main/scala/io/picnicml/doddlemodel/linear/PoissonRegression.scala
  src/main/scala/io/picnicml/doddlemodel/linear/SoftmaxClassifier.scala
Labels: awaits review, enhancement

#99 Fix serialization issues
  src/main/scala/io/picnicml/doddlemodel/data/Feature.scala
  src/main/scala/io/picnicml/doddlemodel/dummy/classification/MostFrequentClassifier.scala
  src/main/scala/io/picnicml/doddlemodel/dummy/classification/StratifiedClassifier.scala
  src/main/scala/io/picnicml/doddlemodel/dummy/classification/UniformClassifier.scala
  src/main/scala/io/picnicml/doddlemodel/dummy/regression/MeanRegressor.scala
  src/main/scala/io/picnicml/doddlemodel/dummy/regression/MedianRegressor.scala
  src/main/scala/io/picnicml/doddlemodel/impute/MeanValueImputer.scala
  src/main/scala/io/picnicml/doddlemodel/impute/MostFrequentValueImputer.scala
  src/main/scala/io/picnicml/doddlemodel/linear/LinearRegression.scala
  src/main/scala/io/picnicml/doddlemodel/linear/LogisticRegression.scala
  src/main/scala/io/picnicml/doddlemodel/linear/PoissonRegression.scala
  src/main/scala/io/picnicml/doddlemodel/linear/SoftmaxClassifier.scala
  src/main/scala/io/picnicml/doddlemodel/pipeline/Pipeline.scala
  src/main/scala/io/picnicml/doddlemodel/preprocessing/Binarizer.scala
  src/main/scala/io/picnicml/doddlemodel/preprocessing/Normalizer.scala
  src/main/scala/io/picnicml/doddlemodel/preprocessing/OneHotEncoder.scala
  src/main/scala/io/picnicml/doddlemodel/preprocessing/RangeScaler.scala
  src/main/scala/io/picnicml/doddlemodel/preprocessing/StandardScaler.scala
  src/main/scala/io/picnicml/doddlemodel/typeclasses/Estimator.scala
Labels: bug
